name: deployment
on:     
   push:   
jobs:
    build:
     name: Build Web
     env:   
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}      
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1   
       
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
         
       - name: Get branch name (pull request)        
         shell: bash
         run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/} | tr / -)" >> $GITHUB_ENV    
       
          
       - name: update password from secrets               
         run: |          
          touch .env
          echo "${{ secrets.LAST_WILL_RETAIN_AND_KEEP_ALIVE_ENV }}"  >> .env
          ls   
         
       - name: Get branch name    
         shell: bash
         run: cat .env
         
       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      
       - name: Build and Push Docker image        
         uses: docker/build-push-action@v2
         with: 	
          context: .  
          dockerfile: Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.BRANCH_NAME }}:${{ env.BRANCH_NAME }}
